[package]
edition = "2021"
name = "zero2prod"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
actix-web = "4.1.0"
reqwest = "0.11.17"
tokio = {version = "1.20.1", features = ["full"]}
